@baseUrl = https://8080-calil05-atividadeapijav-rewe7wa90tk.ws-us115.gitpod.io/

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgVGFyZWZhcyIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzI1MzE0NTgyfQ.0w4_V-QLGP0GXHkhnZBb7GsIWVkWoD3c59LffJDJSmk
###
GET {{baseUrl}}/tarefas

###
POST {{baseUrl}}/tarefas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao": "Criar Formulário",
    "concluido": false
}

###
GET {{baseUrl}}/tarefas/4

###
PUT {{baseUrl}}/tarefas/1
Content-Type: application/json

{
    "descricao": "Testando Alteração",
    "concluido": false
}

###
DELETE {{baseUrl}}/tarefas/1
